# Generated by Django 4.1.7 on 2023-03-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudmid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
